### ISSUE TITLE
jenv fails to set JAVA_HOME

### ISSUE THREAD

**Issue by mcandre** [gcuisinier/jenv#112] opened 2015-08-31 20:40 UTC
jenv appears to fail to set JAVA_HOME, e.g. when using jenv with java 1.7. Am I doing something wrong?

https://github.com/mcandre/dotfiles/blob/master/.bashrc.d/jenv.sh

**Comment by dkowis** [comment] 2015-11-17 22:51
I just ran into this problem as well, but I'm not sure what I'm doing wrong either.

**Comment by jangalinski** [comment] 2016-01-03 11:25
+1

**Comment by dkowis** [comment] 2016-02-02 17:10
Using the export plugin: https://github.com/gcuisinier/jenv#plugins sets the java home properly. Duplicate of #123

**Closed** 2016-05-16 07:22 UTC
